### ISSUE TITLE
Windows (MinGW-w64) build

### ISSUE THREAD

**Issue by hhrhhr** [BatchDrake/sigutils#6]
Hello.
I am trying to compile sigutils for Windows, or rather, already compiled. The following libraries were required: _fftw3, libsndfile, mman-win32_. All of them exist or are compiled without problems under Windows.

A test run of _sutest_ produced the following results:
```
[t:  0] TEST FAILED
[t:  4] TEST FAILED
[t:  9] TEST FAILED
[t: 14] TEST FAILED
[t: 15] TEST FAILED
[t: 16] TEST FAILED
[t: 19] TEST FAILED
[t: 20] TEST FAILED
[t: 21] TEST FAILED
```
Full logs:
 * stdout - https://pastebin.com/epHT5F0m
 * stderr - https://pastebin.com/MgHyEbUX

Some tests do not complete. Should it be so or shouldn't there be mistakes?

**Comment by BatchDrake** [comment]
Many of these tests are broken because of a bunch of optimizations and changes introduced in sigutils during Suscan's development. Many of them are deprecated (especially those concerning PLLs) and should be rewritten. Thank you for reminding me! 

PS I'm surprised you got that far compiling in Windows, I didn't even bother trying.  Please note that I expect Suscan and SigDigger to fail due to unported filesystem calls. Keep me updated on any progress you make with this anyways (your feedback will be useful once I port the whole thing to win32).

**Comment by hhrhhr** [comment]
As I understand it, if you are not using POSIX-only functions and libraries (such as fork), then there will be no big problems with portability.

The progress of "porting" (in fact, these are just minor corrections and a few #ifdef), of course, I will announce a little later.

By the way, do not want to switch to cmake, for example, until the project has grown? This is quite portable, also Qt is switching to this build system completely.

**Comment by BatchDrake** [comment]
Porting to cmake is something that I also have in mind, it's cleaner way
more practical than autotools. However, since I have some other open fronts
(and the current build system works fairly well) I'm delaying it until I
wrap them up.

Anyways, moving both sigutils and Suscan to cmake should be straight
forward. There are a few things to have in mind (e.g. ifdefs, optional volk
support, or deploying data files) but it's something that can practically
be done in less than a weekend.

**Comment by arf20** [comment]
I think this issue also can be closed now, due to the CMake port BatchDrake has done a while back and the hacks and tweaks I did with the utils for Windows compilation under MinGW
